DROP TABLE IF EXISTS SC_USERS;


CREATE TABLE SC_USERS(
USER_ID  varchar(36) NOT NULL,
USER_NAME VARCHAR(200) NOT NULL,
USER_PASSWORD VARCHAR(200) NOT NULL,
ACTIVE TINYINT(1) DEFAULT 0,
PRIMARY KEY (USER_ID)
)ENGINE=InnoDB;

CREATE TABLE SC_ROLES(
ROLE_ID VARCHAR(36) NOT NULL,
ROLE_NAME VARCHAR(200) NOT NULL,
PRIMARY KEY (ROLE_ID)
)ENGINE=InnoDB;



CREATE TABLE SC_USER_ROLES(
USER_ID VARCHAR(36) NOT NULL,
ROLE_ID VARCHAR(36) NOT NULL
)ENGINE=InnoDB;


commit;